### ISSUE TITLE
1.8.0.5 crashes dedicated forge server b1502 on startup

### ISSUE THREAD

**Issue by kreezxil** [Vorquel/Similsax-Transtructors#1]
crash report:
https://gist.github.com/22210cc4a7b19e7cc668

fml server latest:
https://gist.github.com/3a4ad2f83e365d3e6b2a

**Comment by Vorquel** [comment]
A fixed build has been uploaded to Curse. It will be available as soon as it's approved. Sorry for the crash bug.
